/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPassengerRouteImport } from './routes/app.passenger'
import { Route as AppDriverRouteImport } from './routes/app.driver'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppPassengerIndexRouteImport } from './routes/app.passenger.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppTripRideIdRouteImport } from './routes/app.trip.$rideId'
import { Route as AppPassengerBookingsRouteImport } from './routes/app.passenger.bookings'
import { Route as AppPassengerBookRouteImport } from './routes/app.passenger.book'
import { Route as AppAdminVehiclesRouteImport } from './routes/app.admin.vehicles'
import { Route as AppAdminTripsRouteImport } from './routes/app.admin.trips'
import { Route as AppAdminTripHistoryRouteImport } from './routes/app.admin.trip-history'
import { Route as AppAdminPricingServicesRouteImport } from './routes/app.admin.pricing-services'
import { Route as AppAdminPassengersRouteImport } from './routes/app.admin.passengers'
import { Route as AppAdminLiveRouteImport } from './routes/app.admin.live'
import { Route as AppAdminFleetRouteImport } from './routes/app.admin.fleet'
import { Route as AppAdminDriversRouteImport } from './routes/app.admin.drivers'
import { Route as AppAdminBookingsRouteImport } from './routes/app.admin.bookings'
import { Route as AppPassengerBookIndexRouteImport } from './routes/app.passenger.book.index'
import { Route as AppPassengerBookTransportRouteImport } from './routes/app.passenger.book.transport'
import { Route as AppPassengerBookExtendedRouteImport } from './routes/app.passenger.book.extended'
import { Route as AppPassengerBookAssistedRouteImport } from './routes/app.passenger.book.assisted'
import { Route as AppPassengerBookAppointmentRouteImport } from './routes/app.passenger.book.appointment'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPassengerRoute = AppPassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPassengerIndexRoute = AppPassengerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPassengerRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTripRideIdRoute = AppTripRideIdRouteImport.update({
  id: '/trip/$rideId',
  path: '/trip/$rideId',
  getParentRoute: () => AppRoute,
} as any)
const AppPassengerBookingsRoute = AppPassengerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppPassengerRoute,
} as any)
const AppPassengerBookRoute = AppPassengerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppPassengerRoute,
} as any)
const AppAdminVehiclesRoute = AppAdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTripsRoute = AppAdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTripHistoryRoute = AppAdminTripHistoryRouteImport.update({
  id: '/trip-history',
  path: '/trip-history',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPricingServicesRoute = AppAdminPricingServicesRouteImport.update({
  id: '/pricing-services',
  path: '/pricing-services',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPassengersRoute = AppAdminPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLiveRoute = AppAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFleetRoute = AppAdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDriversRoute = AppAdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBookingsRoute = AppAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppPassengerBookIndexRoute = AppPassengerBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPassengerBookRoute,
} as any)
const AppPassengerBookTransportRoute =
  AppPassengerBookTransportRouteImport.update({
    id: '/transport',
    path: '/transport',
    getParentRoute: () => AppPassengerBookRoute,
  } as any)
const AppPassengerBookExtendedRoute =
  AppPassengerBookExtendedRouteImport.update({
    id: '/extended',
    path: '/extended',
    getParentRoute: () => AppPassengerBookRoute,
  } as any)
const AppPassengerBookAssistedRoute =
  AppPassengerBookAssistedRouteImport.update({
    id: '/assisted',
    path: '/assisted',
    getParentRoute: () => AppPassengerBookRoute,
  } as any)
const AppPassengerBookAppointmentRoute =
  AppPassengerBookAppointmentRouteImport.update({
    id: '/appointment',
    path: '/appointment',
    getParentRoute: () => AppPassengerBookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/driver': typeof AppDriverRoute
  '/app/passenger': typeof AppPassengerRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/admin/bookings': typeof AppAdminBookingsRoute
  '/app/admin/drivers': typeof AppAdminDriversRoute
  '/app/admin/fleet': typeof AppAdminFleetRoute
  '/app/admin/live': typeof AppAdminLiveRoute
  '/app/admin/passengers': typeof AppAdminPassengersRoute
  '/app/admin/pricing-services': typeof AppAdminPricingServicesRoute
  '/app/admin/trip-history': typeof AppAdminTripHistoryRoute
  '/app/admin/trips': typeof AppAdminTripsRoute
  '/app/admin/vehicles': typeof AppAdminVehiclesRoute
  '/app/passenger/book': typeof AppPassengerBookRouteWithChildren
  '/app/passenger/bookings': typeof AppPassengerBookingsRoute
  '/app/trip/$rideId': typeof AppTripRideIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/passenger/': typeof AppPassengerIndexRoute
  '/app/passenger/book/appointment': typeof AppPassengerBookAppointmentRoute
  '/app/passenger/book/assisted': typeof AppPassengerBookAssistedRoute
  '/app/passenger/book/extended': typeof AppPassengerBookExtendedRoute
  '/app/passenger/book/transport': typeof AppPassengerBookTransportRoute
  '/app/passenger/book/': typeof AppPassengerBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/driver': typeof AppDriverRoute
  '/app/profile': typeof AppProfileRoute
  '/app/admin/bookings': typeof AppAdminBookingsRoute
  '/app/admin/drivers': typeof AppAdminDriversRoute
  '/app/admin/fleet': typeof AppAdminFleetRoute
  '/app/admin/live': typeof AppAdminLiveRoute
  '/app/admin/passengers': typeof AppAdminPassengersRoute
  '/app/admin/pricing-services': typeof AppAdminPricingServicesRoute
  '/app/admin/trip-history': typeof AppAdminTripHistoryRoute
  '/app/admin/trips': typeof AppAdminTripsRoute
  '/app/admin/vehicles': typeof AppAdminVehiclesRoute
  '/app/passenger/bookings': typeof AppPassengerBookingsRoute
  '/app/trip/$rideId': typeof AppTripRideIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/passenger': typeof AppPassengerIndexRoute
  '/app/passenger/book/appointment': typeof AppPassengerBookAppointmentRoute
  '/app/passenger/book/assisted': typeof AppPassengerBookAssistedRoute
  '/app/passenger/book/extended': typeof AppPassengerBookExtendedRoute
  '/app/passenger/book/transport': typeof AppPassengerBookTransportRoute
  '/app/passenger/book': typeof AppPassengerBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/driver': typeof AppDriverRoute
  '/app/passenger': typeof AppPassengerRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/admin/bookings': typeof AppAdminBookingsRoute
  '/app/admin/drivers': typeof AppAdminDriversRoute
  '/app/admin/fleet': typeof AppAdminFleetRoute
  '/app/admin/live': typeof AppAdminLiveRoute
  '/app/admin/passengers': typeof AppAdminPassengersRoute
  '/app/admin/pricing-services': typeof AppAdminPricingServicesRoute
  '/app/admin/trip-history': typeof AppAdminTripHistoryRoute
  '/app/admin/trips': typeof AppAdminTripsRoute
  '/app/admin/vehicles': typeof AppAdminVehiclesRoute
  '/app/passenger/book': typeof AppPassengerBookRouteWithChildren
  '/app/passenger/bookings': typeof AppPassengerBookingsRoute
  '/app/trip/$rideId': typeof AppTripRideIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/passenger/': typeof AppPassengerIndexRoute
  '/app/passenger/book/appointment': typeof AppPassengerBookAppointmentRoute
  '/app/passenger/book/assisted': typeof AppPassengerBookAssistedRoute
  '/app/passenger/book/extended': typeof AppPassengerBookExtendedRoute
  '/app/passenger/book/transport': typeof AppPassengerBookTransportRoute
  '/app/passenger/book/': typeof AppPassengerBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/driver'
    | '/app/passenger'
    | '/app/profile'
    | '/app/admin/bookings'
    | '/app/admin/drivers'
    | '/app/admin/fleet'
    | '/app/admin/live'
    | '/app/admin/passengers'
    | '/app/admin/pricing-services'
    | '/app/admin/trip-history'
    | '/app/admin/trips'
    | '/app/admin/vehicles'
    | '/app/passenger/book'
    | '/app/passenger/bookings'
    | '/app/trip/$rideId'
    | '/app/admin/'
    | '/app/passenger/'
    | '/app/passenger/book/appointment'
    | '/app/passenger/book/assisted'
    | '/app/passenger/book/extended'
    | '/app/passenger/book/transport'
    | '/app/passenger/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/driver'
    | '/app/profile'
    | '/app/admin/bookings'
    | '/app/admin/drivers'
    | '/app/admin/fleet'
    | '/app/admin/live'
    | '/app/admin/passengers'
    | '/app/admin/pricing-services'
    | '/app/admin/trip-history'
    | '/app/admin/trips'
    | '/app/admin/vehicles'
    | '/app/passenger/bookings'
    | '/app/trip/$rideId'
    | '/app/admin'
    | '/app/passenger'
    | '/app/passenger/book/appointment'
    | '/app/passenger/book/assisted'
    | '/app/passenger/book/extended'
    | '/app/passenger/book/transport'
    | '/app/passenger/book'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/driver'
    | '/app/passenger'
    | '/app/profile'
    | '/app/admin/bookings'
    | '/app/admin/drivers'
    | '/app/admin/fleet'
    | '/app/admin/live'
    | '/app/admin/passengers'
    | '/app/admin/pricing-services'
    | '/app/admin/trip-history'
    | '/app/admin/trips'
    | '/app/admin/vehicles'
    | '/app/passenger/book'
    | '/app/passenger/bookings'
    | '/app/trip/$rideId'
    | '/app/admin/'
    | '/app/passenger/'
    | '/app/passenger/book/appointment'
    | '/app/passenger/book/assisted'
    | '/app/passenger/book/extended'
    | '/app/passenger/book/transport'
    | '/app/passenger/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passenger': {
      id: '/app/passenger'
      path: '/passenger'
      fullPath: '/app/passenger'
      preLoaderRoute: typeof AppPassengerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver': {
      id: '/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passenger/': {
      id: '/app/passenger/'
      path: '/'
      fullPath: '/app/passenger/'
      preLoaderRoute: typeof AppPassengerIndexRouteImport
      parentRoute: typeof AppPassengerRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/trip/$rideId': {
      id: '/app/trip/$rideId'
      path: '/trip/$rideId'
      fullPath: '/app/trip/$rideId'
      preLoaderRoute: typeof AppTripRideIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passenger/bookings': {
      id: '/app/passenger/bookings'
      path: '/bookings'
      fullPath: '/app/passenger/bookings'
      preLoaderRoute: typeof AppPassengerBookingsRouteImport
      parentRoute: typeof AppPassengerRoute
    }
    '/app/passenger/book': {
      id: '/app/passenger/book'
      path: '/book'
      fullPath: '/app/passenger/book'
      preLoaderRoute: typeof AppPassengerBookRouteImport
      parentRoute: typeof AppPassengerRoute
    }
    '/app/admin/vehicles': {
      id: '/app/admin/vehicles'
      path: '/vehicles'
      fullPath: '/app/admin/vehicles'
      preLoaderRoute: typeof AppAdminVehiclesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/trips': {
      id: '/app/admin/trips'
      path: '/trips'
      fullPath: '/app/admin/trips'
      preLoaderRoute: typeof AppAdminTripsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/trip-history': {
      id: '/app/admin/trip-history'
      path: '/trip-history'
      fullPath: '/app/admin/trip-history'
      preLoaderRoute: typeof AppAdminTripHistoryRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/pricing-services': {
      id: '/app/admin/pricing-services'
      path: '/pricing-services'
      fullPath: '/app/admin/pricing-services'
      preLoaderRoute: typeof AppAdminPricingServicesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/passengers': {
      id: '/app/admin/passengers'
      path: '/passengers'
      fullPath: '/app/admin/passengers'
      preLoaderRoute: typeof AppAdminPassengersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/live': {
      id: '/app/admin/live'
      path: '/live'
      fullPath: '/app/admin/live'
      preLoaderRoute: typeof AppAdminLiveRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/fleet': {
      id: '/app/admin/fleet'
      path: '/fleet'
      fullPath: '/app/admin/fleet'
      preLoaderRoute: typeof AppAdminFleetRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/drivers': {
      id: '/app/admin/drivers'
      path: '/drivers'
      fullPath: '/app/admin/drivers'
      preLoaderRoute: typeof AppAdminDriversRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/bookings': {
      id: '/app/admin/bookings'
      path: '/bookings'
      fullPath: '/app/admin/bookings'
      preLoaderRoute: typeof AppAdminBookingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/passenger/book/': {
      id: '/app/passenger/book/'
      path: '/'
      fullPath: '/app/passenger/book/'
      preLoaderRoute: typeof AppPassengerBookIndexRouteImport
      parentRoute: typeof AppPassengerBookRoute
    }
    '/app/passenger/book/transport': {
      id: '/app/passenger/book/transport'
      path: '/transport'
      fullPath: '/app/passenger/book/transport'
      preLoaderRoute: typeof AppPassengerBookTransportRouteImport
      parentRoute: typeof AppPassengerBookRoute
    }
    '/app/passenger/book/extended': {
      id: '/app/passenger/book/extended'
      path: '/extended'
      fullPath: '/app/passenger/book/extended'
      preLoaderRoute: typeof AppPassengerBookExtendedRouteImport
      parentRoute: typeof AppPassengerBookRoute
    }
    '/app/passenger/book/assisted': {
      id: '/app/passenger/book/assisted'
      path: '/assisted'
      fullPath: '/app/passenger/book/assisted'
      preLoaderRoute: typeof AppPassengerBookAssistedRouteImport
      parentRoute: typeof AppPassengerBookRoute
    }
    '/app/passenger/book/appointment': {
      id: '/app/passenger/book/appointment'
      path: '/appointment'
      fullPath: '/app/passenger/book/appointment'
      preLoaderRoute: typeof AppPassengerBookAppointmentRouteImport
      parentRoute: typeof AppPassengerBookRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminBookingsRoute: typeof AppAdminBookingsRoute
  AppAdminDriversRoute: typeof AppAdminDriversRoute
  AppAdminFleetRoute: typeof AppAdminFleetRoute
  AppAdminLiveRoute: typeof AppAdminLiveRoute
  AppAdminPassengersRoute: typeof AppAdminPassengersRoute
  AppAdminPricingServicesRoute: typeof AppAdminPricingServicesRoute
  AppAdminTripHistoryRoute: typeof AppAdminTripHistoryRoute
  AppAdminTripsRoute: typeof AppAdminTripsRoute
  AppAdminVehiclesRoute: typeof AppAdminVehiclesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminBookingsRoute: AppAdminBookingsRoute,
  AppAdminDriversRoute: AppAdminDriversRoute,
  AppAdminFleetRoute: AppAdminFleetRoute,
  AppAdminLiveRoute: AppAdminLiveRoute,
  AppAdminPassengersRoute: AppAdminPassengersRoute,
  AppAdminPricingServicesRoute: AppAdminPricingServicesRoute,
  AppAdminTripHistoryRoute: AppAdminTripHistoryRoute,
  AppAdminTripsRoute: AppAdminTripsRoute,
  AppAdminVehiclesRoute: AppAdminVehiclesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppPassengerBookRouteChildren {
  AppPassengerBookAppointmentRoute: typeof AppPassengerBookAppointmentRoute
  AppPassengerBookAssistedRoute: typeof AppPassengerBookAssistedRoute
  AppPassengerBookExtendedRoute: typeof AppPassengerBookExtendedRoute
  AppPassengerBookTransportRoute: typeof AppPassengerBookTransportRoute
  AppPassengerBookIndexRoute: typeof AppPassengerBookIndexRoute
}

const AppPassengerBookRouteChildren: AppPassengerBookRouteChildren = {
  AppPassengerBookAppointmentRoute: AppPassengerBookAppointmentRoute,
  AppPassengerBookAssistedRoute: AppPassengerBookAssistedRoute,
  AppPassengerBookExtendedRoute: AppPassengerBookExtendedRoute,
  AppPassengerBookTransportRoute: AppPassengerBookTransportRoute,
  AppPassengerBookIndexRoute: AppPassengerBookIndexRoute,
}

const AppPassengerBookRouteWithChildren =
  AppPassengerBookRoute._addFileChildren(AppPassengerBookRouteChildren)

interface AppPassengerRouteChildren {
  AppPassengerBookRoute: typeof AppPassengerBookRouteWithChildren
  AppPassengerBookingsRoute: typeof AppPassengerBookingsRoute
  AppPassengerIndexRoute: typeof AppPassengerIndexRoute
}

const AppPassengerRouteChildren: AppPassengerRouteChildren = {
  AppPassengerBookRoute: AppPassengerBookRouteWithChildren,
  AppPassengerBookingsRoute: AppPassengerBookingsRoute,
  AppPassengerIndexRoute: AppPassengerIndexRoute,
}

const AppPassengerRouteWithChildren = AppPassengerRoute._addFileChildren(
  AppPassengerRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDriverRoute: typeof AppDriverRoute
  AppPassengerRoute: typeof AppPassengerRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppTripRideIdRoute: typeof AppTripRideIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDriverRoute: AppDriverRoute,
  AppPassengerRoute: AppPassengerRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppTripRideIdRoute: AppTripRideIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
